### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by imRonakPatel** [mikededo/Weight_Tracker#3]
1) Widgets that are causing issues are Calendar and Chart. The problem is in the chart where data used for calculations are limited until the present day. Instead of today or previous days if the user adds data for the next day chart is not able to show that data. The solution for this, you can restrict the user to add data only for today and past days. Make another calendar widget for Goal data where users can select any days.

```
widget.helper.addType == AddWeightType.Goal
        ? CalendarforGoal(
            selectedDateTime: _selectedDate,
            onDayPressed: (DateTime date, _) {
              setState(() => _selectedDate = date);
            },
          )
        : Calendar(
            selectedDateTime: _selectedDate,
            onDayPressed: (DateTime date, _) {
              setState(() => _selectedDate = date);
            },
          );
```
//      maxSelectedDate: DateTime.now(), for Calendar

2) Another problem: when minValue is equal to the maxValue, the chart is not showing any data because the chart is dependent on the min-max difference. for that, you can simply add a condition if minValue=maxValue and remove horizontalInterval for that case. 

3) Lastly, just add one more condition to prevent users from accessing the chart if the data are not enough.

```
state.weightCollection.length < 2
                        ? Padding(
                            padding: EdgeInsets.only(top: 15),
                            child: Container(
                              padding: EdgeInsets.all(15),
                              color: Colors.black,
                              height: 180,
                              child: Center(
                                child: Text(
                                  'Not enough data! Add more data to show graph.',
                                  style: Theme.of(context).textTheme.bodyText1,
                                  textAlign: TextAlign.center,
                                ),
                              ),
                            ),
                          )
                        : Tile(
                            margin: const EdgeInsets.only(top: 12.0),
                            child: WeightLineChart(state.weightCollection),
                          ),

```
4) There are few bugs still present ( if the user will add data before the past seven days(if current seven days data are empty) chart will throw an error.) 

Anyway, these are my suggestions, it's not ideal but it will work.

**Comment by mikededo** [comment]
Hey man!

I appreciate you taking a look over the project :smile:!

Now I'm pretty busy with the university and everything! As soon as I can I will take a look!
