### ISSUE TITLE
Error message saying when running the smoothSurvey command it says the  Exist regions in data but not in the Amat

### ISSUE THREAD

**Issue by Cheni-design** [mikededo/Weight_Tracker#4]
smoothed <- smoothSurvey(data =  COD_data, geo = COD_shp,
                     Amat = mat, family = "binomial", responseVar = "hyper",
                     strataVar = NULL, weightVar = NULL, regionVar = "NAME_2",
                     clusterVar = NULL, hyper = NULL, CI = 0.95)

I have already created the adjacent matrix using getmat but it gives this error ( Exist regions in data but not in the Amat) after running the above code

**Comment by mikededo** [comment]
Hmm hello!

Is this issue related with this project? 😄

**Comment by Cheni-design** [comment]
No it's not

**Comment by mikededo** [comment]
Then why did you post it? 😅
